# compose file to make it easy
# to run the whole group of programs
# services are ordered by number of dependencies


services:
  db:
    image: postgres
    # Not sure if these two are necessary. Taken from postgres example.
    restart: always
    shm_size: 128mb
    # Environment variables
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: readings_db
    # Mount local db-data folder onto the container at runtime.
    # Allows for persistent data since the data lives on our own physical PC
    volumes:
      - ./db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d readings_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
   
  restapi:
    build:
      context: ./restapi
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=readings_db
      - DB_USER=user
      - DB_PASS=pass
    #- DATABASE_URL=postresql://admin:password123@db:5432/pipeline_db
    depends_on:
      db:
        condition: service_healthy # wait until the database is running and good to go, not just until the container is created 

  sensor:
    # Specifies location of dockerfile
    build:
      context: ./sensor
    # These environment variables store endpoint URLs, which is handy 
    environment: 
      - SAMPLER_URL=http://sampler:3000/
    # depends_on allows for dependencies and build order in docker compose
    depends_on: 
      sampler:
        condition: service_healthy # wait for sampler to start up
  
  sampler:
    build:
      context: ./sampler
    environment:
      - TRANSFORMER_HOST=transformer
      - TRANSFORMER_PORT=5000
      # - TRANSFORMER_URL=http://transformer:5000/data
    depends_on:
    - transformer
    ports: 
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  transformer:
    build:
      context: ./transformer
    environment:
      - TRANSFORMER_HOST=transformer
      - TRANSFORMER_PORT=5000
      - RESTAPI_URL=http://restapi:5001/temperature
    depends_on:
      - restapi


