name: Run Sensor Simulation
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run Sampler
        run: nohup node sampler.js &

      - name: Compile Sensor and Tests
        run: javac Sensor.java
              javac -cp ".:junit-jupiter-api-5.10.0.jar" TestCases.java

      - name: Download JUnit
        run: |
          curl -L -o junit-jupiter-api-5.10.0.jar https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.10.0/junit-jupiter-api-5.10.0.jar
          curl -L -o junit-jupiter-engine-5.10.0.jar https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.10.0/junit-jupiter-engine-5.10.0.jar
          curl -L -o junit-platform-console-standalone-1.10.2.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar

      - name: Compile Tests
        run: javac -cp ".:junit-jupiter-api-5.10.0.jar" TestCases.java

      - name: Run Sensor
        run: java Sensor

      - name: Run Unit Tests
        run: |
          java -jar junit-platform-console-standalone-1.10.2.jar \
            --class-path ".:junit-jupiter-api-5.10.0.jar:junit-jupiter-engine-5.10.0.jar" \
            --scan-class-path \
            --include-classname '.*TestCases'      
